name: Golang

on:
  workflow_call:
    inputs:
      golang_version:
        required: true
        type: string

jobs:
  check:
    name: Lint and Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: Checkout code

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.golang_version }}

    - name: Lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest
        args: -v --timeout 5m


  test:
    name: Unit Test
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.golang_version }}
      - name: Run Tests
        run: make test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.golang_version }}
      - name: Run Build
        run: make build
